apiVersion: v1
kind: Secret

metadata:
  name: payment-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: abusayath
  JWT_SECRET: SZ2UaRvv6HQ2h0ZTZPHTJTyZ9TRiN46t8wa+x2/ijK0=
