apiVersion: v1
kind: Secret

metadata:
  name: payment-secret

type: Opaque

stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.datasourceUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.datasourcePassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}